name: inventory_app
description: Inventory app with Firebase and Cloudinary
publish_to: "none"
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.6
  image_picker: ^0.8.7+6
  uuid: ^4.5.1
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.2.3
  intl: ^0.17.0
  fl_chart: ^0.69.0
  google_fonts: ^4.0.4
  flutter_typeahead: ^5.2.0
  path_provider: ^2.1.5
  open_file: ^3.5.10
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  pdf: ^3.11.3
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  dartz: ^0.10.1
  rxdart: ^0.27.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  

flutter:
  uses-material-design: true
  # assets: 
  #   - lib/assets/logo.png
  #   - lib/assets/login-signup-background.png
  #   - lib/assets/background.png
  #   - lib/assets/background2.png
